name: Embed Encrypted libbgmi.so into PNG

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  embed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install Pillow pycryptodome

      - name: Run embedding script
        run: python embed.py

      - name: Upload output image
        uses: actions/upload-artifact@v4
        with:
          name: stego-image
          path: stego.png
