name: Embed Encrypted libbgmi.so into PNG

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  embed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install Pillow pycryptodome
      - run: python embed.py
      - uses: actions/upload-artifact@v4
        with:
          name: stego-image
          path: stego.png
